spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/product-manager
    username: root
    password: 13q1w2e3r4t5z6BE
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
flyway:
  url: jdbc:mariadb://localhost:3306/product-manager
  schemas: product-manager
  user: "root"
  password:

